name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        mode:
          - debug
          - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: wasm-bindgen-cli

      - name: Toggle rustc mode
        run: |
          if [ ${{ matrix.mode }} == debug ]; then
            echo "TEST_MODE=" >> $GITHUB_ENV
          else
            echo "TEST_MODE=--release" >> $GITHUB_ENV
          fi

      - name: Tests Wasm32
        run: |
          export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=$HOME/.cargo-install/wasm-bindgen-cli/bin/wasm-bindgen-test-runner
          cargo test $TEST_MODE -p openmls -vv --target wasm32-unknown-unknown -F js

      - name: Tests Wasm32 with libcrux provider
        env:
          RUSTFLAGS: --cfg getrandom_backend="wasm_js"
        run: |
          export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=$HOME/.cargo-install/wasm-bindgen-cli/bin/wasm-bindgen-test-runner
          cargo test $TEST_MODE -p openmls -vv --target wasm32-unknown-unknown -F js,libcrux-provider,libcrux-provider-js
